docker cp o213:/opt/oracle/admin/free/scripts/CreateClustDBViews.sql .
docker cp o213:/opt/oracle/admin/free/scripts/CreateDB.sql .
docker cp o213:/opt/oracle/admin/free/scripts/CreateDBCatalog.sql .
docker cp o213:/opt/oracle/admin/free/scripts/CreateDBFiles.sql .
docker cp o213:/opt/oracle/admin/free/scripts/JServer.sql .
docker cp o213:/opt/oracle/admin/free/scripts/PDBCreation.sql .
docker cp o213:/opt/oracle/admin/free/scripts/context.sql .
docker cp o213:/opt/oracle/admin/free/scripts/cwmlite.sql .
docker cp o213:/opt/oracle/admin/free/scripts/free.sh .
docker cp o213:/opt/oracle/admin/free/scripts/free.sql .
docker cp o213:/opt/oracle/admin/free/scripts/init.ora .
docker cp o213:/opt/oracle/admin/free/scripts/interMedia.sql .
docker cp o213:/opt/oracle/admin/free/scripts/lockAccount.sql .
docker cp o213:/opt/oracle/admin/free/scripts/ordinst.sql .
docker cp o213:/opt/oracle/admin/free/scripts/plug_freepdb1.sql .
docker cp o213:/opt/oracle/admin/free/scripts/postDBCreation.sql .
docker cp o213:/opt/oracle/admin/free/scripts/postPDBCreation_freepdb1.sql .
docker cp o213:/opt/oracle/admin/free/scripts/spatial.sql .

